/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  SepoliaConnector,
  SepoliaConnectorInterface,
} from "../../contracts/SepoliaConnector";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_predictionMarket",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "marketId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "outcomeIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "placeCrossChainBet",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "predictionMarket",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "zetaChainId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052611b5960015534801561001657600080fd5b506040516102af3803806102af8339810160408190526100359161005a565b600080546001600160a01b0319166001600160a01b039290921691909117905561008a565b60006020828403121561006c57600080fd5b81516001600160a01b038116811461008357600080fd5b9392505050565b610216806100996000396000f3fe6080604052600436106100345760003560e01c8063566483c614610039578063b1e5032814610062578063def114b614610077575b600080fd5b34801561004557600080fd5b5061004f60015481565b6040519081526020015b60405180910390f35b610075610070366004610148565b6100af565b005b34801561008357600080fd5b50600054610097906001600160a01b031681565b6040516001600160a01b039091168152602001610059565b604080516020810185905290810183905233606082015260009060800160408051601f19818403018152908290526000805463c852269160e01b84529193506001600160a01b039091169163c8522691916101109186908690600401610174565b600060405180830381600087803b15801561012a57600080fd5b505af115801561013e573d6000803e3d6000fd5b5050505050505050565b60008060006060848603121561015d57600080fd5b505081359360208301359350604090920135919050565b60018060a01b038416815260006020848184015260606040840152835180606085015260005b818110156101b65785810183015185820160800152820161019a565b818111156101c8576000608083870101525b50601f01601f1916929092016080019594505050505056fea26469706673582212207129e6f4707a3b9cc8905a316f61a08f8137e582398e44cacd9adb4e2e652c9b64736f6c63430008070033";

type SepoliaConnectorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SepoliaConnectorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SepoliaConnector__factory extends ContractFactory {
  constructor(...args: SepoliaConnectorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _predictionMarket: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_predictionMarket, overrides || {});
  }
  override deploy(
    _predictionMarket: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_predictionMarket, overrides || {}) as Promise<
      SepoliaConnector & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SepoliaConnector__factory {
    return super.connect(runner) as SepoliaConnector__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SepoliaConnectorInterface {
    return new Interface(_abi) as SepoliaConnectorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SepoliaConnector {
    return new Contract(address, _abi, runner) as unknown as SepoliaConnector;
  }
}
